// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using W_CC.Infra.Data.ContextoConfig;

namespace W_CC.Infra.Data.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200523025650_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("W_CC.Dominio.Model.ContasCorrentes", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("Agencia")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<int>("Conta")
                        .HasColumnType("int")
                        .HasMaxLength(10);

                    b.Property<byte[]>("PessoaId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("UltimaMovimentacao")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("Agencia", "Conta")
                        .IsUnique();

                    b.ToTable("ContasCorrentes");
                });

            modelBuilder.Entity("W_CC.Dominio.Model.Operacoes", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("ContaCorrenteId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime");

                    b.Property<int>("TipoOperacao")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaCorrenteId");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("W_CC.Dominio.Model.Pessoas", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("CPF")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("W_CC.Dominio.Model.ContasCorrentes", b =>
                {
                    b.HasOne("W_CC.Dominio.Model.Pessoas", "Pessoa")
                        .WithMany("ContasCorrentes")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("W_CC.Dominio.Model.Operacoes", b =>
                {
                    b.HasOne("W_CC.Dominio.Model.ContasCorrentes", "ContaCorrente")
                        .WithMany("Operacoes")
                        .HasForeignKey("ContaCorrenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
